import "~/assets/styles/globals.css";

import * as React from "react";
import { PropsWithChildren } from "react";

import Navbar from "~/app/_components/navbar";
import Sidebar from "~/app/_components/sidebar";
import { ThemeProvider } from "~/presentation/providers/theme-provider";
import { Toaster } from "~/presentation/ui/sonner";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <div>
            <div className="hidden lg:fixed lg:inset-y-0 lg:z-50 lg:flex lg:w-60 lg:flex-col">
              <Sidebar />
            </div>

            <div className="lg:pl-60">
              <div className="sticky top-0 z-40 lg:mx-auto lg:px-6">
                <Navbar />
              </div>

              <main className="py-4">
                <div className="px-2 sm:px-4 lg:px-6">{props.children}</div>
              </main>
            </div>
          </div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
