import "~/assets/styles/globals.css";

import { PropsWithChildren } from "react";

import { MainNav } from "~/app/_components/main-nav";
import { UserNav } from "~/app/_components/user-nav";
import { ThemeProvider } from "~/presentation/providers/theme-provider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <div className="border-b">
            <div className="flex h-16 items-center px-4">
              <MainNav className="mx-6" />
              <div className="ml-auto flex items-center space-x-4">
                <UserNav />
              </div>
            </div>
          </div>

          {props.children}
        </ThemeProvider>
      </body>
    </html>
  );
}
