import "~/assets/styles/globals.css";

import { PropsWithChildren } from "react";

import { ThemeProvider } from "~/presentation/providers/theme-provider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>{props.children}</ThemeProvider>
      </body>
    </html>
  );
}
